### ISSUE TITLE
Prototype GitHub Pages

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#102]
Prototype using GitHub Pages for hosting the website to see if it is a viable alternative to self-hosting.

**Comment by molinaro-m** [comment]
I have two concerns, _issues_, on this:
1. hosting/self-hosting should be discussed with Exec
2. why do we need an external service to deploy static pages (since we anyway need a server for documents, wiki and mails)?

**Comment by JeremyMcCormick** [comment]
One issue with GitHub Pages is that it will make the preview sites that we have been generating for PRs more complicated to generate. Though I'm not sure this is a "must have" feature given that previews can be generated and checked locally by developers.

**Comment by gmantele** [comment]
Although I know GitHub pages are simple to set-up and to manage, I tend to me more in favor of a self-hosting solution.

- @JeremyMcCormick , about your 1st point. I think the problem of deployment speed is due to all images from newsletters. This could probably be solved with some nice options of `rsync`: when a file is present, don't copy it. This solution could probably be applied to other resources (e.g. PDF, ...). This way, we should see a high deployment improvement. One has to test to verify this hypothesis.
- Again, about images, we may have an issue in the future. I think there may be a maximum limit for the repository/commit size. I've experienced such error message from Git when I submitted a large video on the CDS website. The self-hosting solution helped a lot to solve this issue: I've just copied the video manually somewhere on our server instead of the Git repository. The difference with the IVOA website is that we use GitLab instead of GitHub for the CDS website. However, that may be something to keep in mind for the future. I know there are some Git solution to solve this size issue (e.g. [git-lfs](https://git-lfs.com/)) but they have a price ; generally they are heavy to set up on each local repository clone. So it would be better not to make our pipeline even more complicated with such hack-y solution.
- Yes, I agree not depending on an institutional infrastructure seems better in theory. Although the GitHub server are probably more robust, stable and secure, a self-hosting solution offers us more flexibility and more possibilities (e.g. database, application server, ...) that we have to be aware of.
- I agree that the static website, the IVOA doc. repository, wiki and emails can be set up on separated servers, because as you said they are different applications. We just have to be careful not to break the CSS style between them as well as the eventual communication between them. For instance, one question we have to answer is, if we move to GitHub Pages, how to share the CSS stylesheet (and possible Tailwind resources/templates) with the IVOA doc. repository? Should we set up a CI just to copy this stylesheets (and related images and fonts) on the IVOA doc. repo. server (as we do now)? Alternatively, should we create a Web API for the IVOA doc. repo. in order to dynamically build with Javascript the IVOA doc. page?
- Anyway, I foresee some resistance from some IVOA members: GitHub = Microsoft. These members may disagree in making the IVOA website a "product" of Microsoft (especially with the fear that Microsoft might change things regarding GitHub in the future).
- Finally, regarding the static IVOA website (I am not speaking about the IVOA doc. repo.), as far as I can remember, this solution has always worked really fine until now. So, is it really so risky to keep this hosting solution, knowing that if we change for GitHub Pages, we will have to educate all our users and contributors to change their bookmark toward the IVOA website (and, from CDS experience, this may take time)?

**Comment by molinaro-m** [comment]
> > I have two concerns, _issues_, on this:
> > 
> > 1. hosting/self-hosting should be discussed with Exec
> 
> I would be interested in feedback from this.

This is where (again) we need a vconf among the people working on this effort, to define what to ask to whom.
I'll try to set up an email about this, but I'm quite busy, so, if someone gets there before me... better
 
> > 2. why do we need an external service to deploy static pages (since we anyway need a server for documents, wiki and mails)?
> 
> There are some definite advantages compared to the current hosting situation:

I'll try to add my view, even if possible already superceded by Gregory's

> 1. Deployment would be much faster. Currently, copying over the entire site takes about 3 minutes.

Is it really an issue, 3 minutes, considering that the actual move from preview to production has to be managed manually anyway?

> 2. The success of the deployment would not be dependent upon external server load or connectivity, a problem which we saw when many people were working on the site at once.

Same: I don't think we can use Sydney's experience as the metrics, also considering the ssh bombing that happened.

> 3. We could have better and more seamless integration with GitHub branches, tags and updates to `main`.

If it were for the preview staging, I'd agree, for the production one I don't think this is an issue.

> 4. GitHub pages is free for public repositories.

Yes, but it configures as a vendor lock-in anyway, if we dismantle the self-hosted one.
IVOA is an organisation in itself, not a github-organisation.

> 5. The site would basically be infinitely scalable.

Scalable with respect to: user access? mirrors spread around the globe?
Again, this is not a big-data infrastructure.

> 6. The hosting would not depend on a particular institutional infrastructure and the status of any IVOA member in terms of their employment or affiliation.

But the infrastructure will need to be there or other services anyway, so the effort is on maintenance, non the servers.

> 7. The security would be improved compared with self-hosting, as it would not rely on configuration of an external server and its possible vulnerabilities. We would be much better protected against common security threats like DDOS attacks.

I'm not sure, you can say the same with GMail, and we had bad issues with their servers, similarly as the ones we had with self hosted ones.

> 8. Burden on a particular IVOA member to coordinate or respond to technical issues based on institutional hosting would be alleviated. Anyone who understands how GitHub Pages works could make technical contributions and deal with issues.

The point, to me, is that the big effort is on curation of the content, not the technical part.
This is what we suffer a lot.
Hugo & github helps there, other commercial commitments I don't think will simplify or help, only add more trouble,

> As far as documents, wiki and mails, I view those as separate applications. We need not host the site externally just because of how those are currently setup, and, as far I'm aware, there's no technical requirement that any of these be co-hosted.

CSS points raised by Gregory apart, I don't think DNS management and httpd rewrite rules will be simpler moving from self-hosted to mixed-hosting.

I know I'm quite strict here, but it's also a matter of communication channels, I don't think a github issues is really the place for this discussion.

**Comment by JeremyMcCormick** [comment]
This wasn't meant to be a referendum on current hosting, so I am locking and closing. We can discuss in other communication channels.
